version: '3'

tasks:
  run:
    cmds:
      - go run main.go
  build:
    cmds:
      - go install ./...
  lint:
    cmds:
      - golangci-lint run
  test:
    cmds:
      - go test ./... -count=1 -v